Add install files to the build
neutrinolabs/pulseaudio-module-xrdp pull request #64
Opened 2021-10-20 10:25 UTC by matt335672

Adds installation files to the build.

`make install` now also creates the following files:-

- /usr/libexec/pulseaudio-module-xrdp/load_pa_modules.sh which dynamically loads the xrdp pulseaudio modules
- /etc/xdg/autostart/pulseaudio-xrdp.desktop which calls to the above for any desktop which supports the [XDG autostart](https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html) specification.

This PR is dependent on #59 

This method of loading pulseaudio drivers is compatible with existing systems, and removes the need for PA_SCRIPT to be set in `/etc/xrdp/sesman.ini` for all systems.

2021-11-01 05:40 UTC, metalefty commented on instfiles/Makefile.am
> +xdgautostartdir=/etc/xdg/autostart
In FreeBSD, sysconfdir is the location for that. However, as far as I read the specifications, `/etc/xdg` is defined in the specification. I think the current value is correct.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#referencing

So maybe FreeBSD's `$sysconfdir/xdg` is a kind of overrides path by local patches. I'll patch to this `Makefile.am` when I create FreeBSD package for this pulse module.

2021-11-01 05:47 UTC, metalefty commented on instfiles/Makefile.am
> +xdgautostartdir=/etc/xdg/autostart
FYI, parcellite pacakge installs its autostart file into `/usr/local/etc/xdg/autostart/parcellite-startup.desktop`.

All those paths are prefixed by ports prefix (`=/usr/local`).
https://cgit.freebsd.org/ports/tree/deskutils/parcellite/pkg-plist#n2

Anyway, maybe this is FreeBSD specific stuff. I'm fine this as-is. I'll apply some local patches for FreeBSD.

2021-11-01 05:48 UTC, metalefty approved these changes

2021-11-01 11:59 UTC, matt335672 commented on instfiles/Makefile.am
> +xdgautostartdir=/etc/xdg/autostart
I think you're right in that this is probably FreeBSD specific for the ports. Personally I think it's a good idea, but Linux (and the specification) doesn't seem to support it.

FreeBSD is a supported platform, so I think we should get this in the base, rather than having a patch for it. Should we copy this logic from xrdp/configure.ac do you think?

https://github.com/neutrinolabs/xrdp/blob/4ea93beebb15c225adbec7c12f1f2cd4f1d9ea67/configure.ac#L22-L47

Then in instfiles/Makefile.am:-

```
if FREEBSD
    xdgautostartdir=$sysconfdir/xdg/autostart
else
    # Linux doesn't support /usr/local/etc/xdg
    xdgautostartdir=/etc/xdg/autostart
endif
```

Should be easy enough to test.

2021-11-04 14:11 UTC, matt335672 commented
@metalefty - I'm aware you've approved this, but related to your comment above I've added an extra command line switch to configure to make FreeBSD easier to support.

The following now works for me on FreeBSD 13.0:-

```
./bootstrap
CFLAGS="-I/usr/local/include" ./configure \
    --with-xdgautostart-dir=/usr/local/etc/xdg/autostart \
    PULSE_DIR=/usr/ports/audio/pulseaudio/work/pulseaudio-13.0
make
sudo make install
```

If you're happy with this, I'll start merging in the other changes to devel.

2021-11-05 02:11 UTC, metalefty commented
@matt335672 Thanks, I'm fine with that.

2021-11-05 07:03 UTC, metalefty requested changes

2021-11-05 07:03 UTC, metalefty commented on instfiles/load_pa_modules.sh
> +PACTL=/usr/bin/pactl
Happy if we can avoid this hardcoded path of `pactl`.

2021-11-05 10:32 UTC, matt335672 commented on instfiles/load_pa_modules.sh
> +PACTL=/usr/bin/pactl
Good point - this will be broken on FreeBSD of course.

I'll assume it's in the PATH. It's not a privileged script, and if the pa utils aren't in the PATH for the desktop, the user will have other problems anyway.

2021-11-05 10:36 UTC, matt335672 commented on instfiles/load_pa_modules.sh
> +PACTL=/usr/bin/pactl
I'll look into this a bit further - my FreeBSD testing was OK, so something's happening here I'm not expecting

2021-11-05 11:29 UTC, matt335672 commented on instfiles/load_pa_modules.sh
> +PACTL=/usr/bin/pactl
Got it - under FreeBSD, the PULSE_SCRIPT environment variable is loading the xrdp drivers. The `load_pa_modules.sh` fails, but that doesn't matter.

Removing the PULSE_SCRIPT definition is causing some problems. I'll get this working on FreeBSD, re-test on a couple of Linuxes and then post an updated script for re-review.

2021-11-05 12:47 UTC, matt335672 commented
Script now works OK with my FreeBSD 13 testing, with or without the PULSE_SCRIPT setting.

A further change was required in that on my FreeBSD VM without PULSE_SCRIPT set, the pulseaudio daemon was using the built-in sound card (oss_output.dsp0) rather than the xrdp channel. I've now set the default source and sink to be the xrdp devices if we're in an xrdp session. I can't think of any reason why the user wouldn't want to do this anyway.

I've also retested on Ubuntu 20.04, Ubuntu 18.04, Debian Buster and CentOS 8 with or without the PULSE_SCRIPT setting. They all seem OK, so that leaves the way open to removing that setting in a later version of xrdp.

2021-11-09 00:23 UTC, metalefty commented on instfiles/load_pa_modules.sh
> +status=0
It doesn't seem the `status` is not referred from anywhere, is this correct?

2021-11-09 08:54 UTC, matt335672 commented on instfiles/load_pa_modules.sh
> +status=0
Good catch. Last line should be `exit $status`. I'll fix it up and do some squashing.

2021-11-09 09:44 UTC, metalefty approved these changes

2021-11-09 10:48 UTC, merged