plasma 5.26 does not like PA_PROP_DEVICE_CLASS abstract
neutrinolabs/pulseaudio-module-xrdp pull request #91
Opened 2023-01-30 18:24 UTC by akarl10

according to doxygen only
  "sound", "modem", "monitor", "filter"
are allowed. Use sound as this is the most appropriate

2023-01-31 07:30 UTC, akarl10 commented
actually for plasma 5.27 to work correctly it seems that we need to create "cards".
comparing to raop there is created a card with a port that then has a sink.
In this case probably we need to do the same.

I will have a look when I find some time

2023-02-02 11:39 UTC, matt335672 requested changes
Sorry about delay - been on other things. A few comments below, only one major.

2023-02-02 11:39 UTC, matt335672 commented on src/module-xrdp-sink.c
> +    pa_device_port_new_data_done(&data);
Line 151 and a couple of others have trailing blanks. Please remove.

2023-02-02 11:39 UTC, matt335672 commented on src/module-xrdp-sink.c
> +
We never got round to a coding style for this module. However, single line if's in the original source always have braces around the block, so I suggest sticking with that.

2023-02-02 11:39 UTC, matt335672 commented on src/module-xrdp-sink.c
> +    pa_device_port_new_data_set_type(&data, PA_DEVICE_PORT_TYPE_NETWORK);
pa_device_port_new_data_set_type() was added for PA 14 (pull request [here](/pulseaudio/pulseaudio/commit/feee531c2bcc3618b62a7fbb140b80043c680dc4)). This line fails to compile on Ubuntu 20.04 and CentOS 7. I'd suggest bracketing it with a version test like this:-

```c
#if defined(PA_CHECK_VERSION) && PA_CHECK_VERSION(14, 0, 0)
    pa_device_port_new_data_set_type(&data, PA_DEVICE_PORT_TYPE_NETWORK);
#endif
```

2023-02-02 11:39 UTC, matt335672 commented on src/module-xrdp-source.c
> +    pa_device_port_new_data_set_type(&data, PA_DEVICE_PORT_TYPE_NETWORK);
As before:-

```c
#if defined(PA_CHECK_VERSION) && PA_CHECK_VERSION(14, 0, 0)
    pa_device_port_new_data_set_type(&data, PA_DEVICE_PORT_TYPE_NETWORK);
#endif
```

2023-02-02 12:56 UTC, akarl10 commented on src/module-xrdp-sink.c
> +
ok, but I will do that only for the code I made. Else it might make sense to copy over run_astyle from xrdp?

2023-02-02 13:42 UTC, matt335672 commented on src/module-xrdp-sink.c
> +
Just stick with yours for now. The run_astyle is very much a TBD. I don't know how much longer there will be a lot of interest in this, now pipewire is about.

2023-02-02 14:16 UTC, akarl10 commented on src/module-xrdp-sink.c
> +
agree. especially since pipewire allows external building of modules and so remote audio will hopefully work by default since not "self" building is needed anymore

2023-02-06 11:01 UTC, merged